// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMBP.App.Infrastructure.Models;

public partial class Application
{
    [Key]
    public Guid UID { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [InverseProperty("ApplicationU")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}