// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMBP.App.Infrastructure.Models;

[Index("Name", "Language", Name = "IX_Translations", IsUnique = true)]
public partial class Translation
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(200)]
    public string Name { get; set; } = null!;

    [StringLength(2)]
    [Unicode(false)]
    public string Language { get; set; } = null!;

    public string Value { get; set; } = null!;
}