// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMBP.App.Infrastructure.Models;

public partial class UserRole
{
    [Key]
    public Guid UID { get; set; }

    public Guid UserUID { get; set; }

    public Guid ApplicationUID { get; set; }

    public byte Role { get; set; }

    [ForeignKey("ApplicationUID")]
    [InverseProperty("UserRoles")]
    public virtual Application ApplicationU { get; set; } = null!;

    [ForeignKey("UserUID")]
    [InverseProperty("UserRoles")]
    public virtual User UserU { get; set; } = null!;
}