// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMBP.App.Infrastructure.Models;

public partial class User
{
    [Key]
    public Guid UID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CID { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string UserName { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string FirstName { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? MiddleName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LastName { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime RegistrationDate { get; set; }

    public byte Role { get; set; }

    public byte Status { get; set; }

    [InverseProperty("UserU")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}